# Generated by Django 3.0.5 on 2020-05-25 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='age',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='contact',
        ),
    ]
