# Generated by Django 3.0.5 on 2020-05-27 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200525_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='user_name',
        ),
        migrations.AlterField(
            model_name='signup',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
