# Generated by Django 3.0.5 on 2020-05-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200527_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='tempassword',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
